server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/placeapp
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

    show-sql: true

